#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------

ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif

TOPDIR ?= $(CURDIR)
DEBUG ?= 0
include $(DEVKITARM)/3ds_rules

#---------------------------------------------------------------------------------
# Project configuration
#---------------------------------------------------------------------------------
TARGET		:=	$(notdir $(CURDIR))
BUILD		:=	build
SOURCES		:=	source source/rooms
DATA		:=	data
INCLUDES	:=	include source source/rooms
GRAPHICS	:=	gfx
ROMFS		:=	romfs

# Graphics that must be linked directly into the executable.
# Everything else under GRAPHICS will be placed in RomFS.
MEMGFX		:=	gfx/hud/gfx_hud.t3s

#---------------------------------------------------------------------------------
# options for code generation
#---------------------------------------------------------------------------------
ARCH	:=	-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft

CFLAGS	:=	-g -Wall -O2 -mword-relocations \
			-ffunction-sections \
			$(ARCH)

ifeq ($(DEBUG),1)
	CFLAGS += -DDEBUG
endif
CFLAGS	+=	$(INCLUDE) -D__3DS__

CXXFLAGS	:= $(CFLAGS) -fno-rtti -fno-exceptions -std=gnu++11

ASFLAGS	:=	-g $(ARCH)
LDFLAGS	=	-specs=3dsx.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)

LIBS	:= -lcitro2d -lcitro3d -lctru -lm -lvorbisidec -logg

#---------------------------------------------------------------------------------
# Libraries
#---------------------------------------------------------------------------------
LIBDIRS := $(CTRULIB) $(DEVKITPRO)/portlibs/3ds

#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add
# additional rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(TARGET)
export TOPDIR	:=	$(CURDIR)
export DEPSDIR	:=	$(CURDIR)/$(BUILD)

#---------------------------------------------------------------------------------
# Source files
#---------------------------------------------------------------------------------
CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
PICAFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.v.pica)))
SHLISTFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.shlist)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

#---------------------------------------------------------------------------------
# Graphics
#---------------------------------------------------------------------------------

# Find every .t3s recursively under GRAPHICS
GFXFILES	:=	$(foreach dir,$(GRAPHICS),$(shell find $(dir) -type f -name '*.t3s'))

TIMELINE_GFX := $(filter gfx/timelines/%,$(GFXFILES))

# Everything except MEMGFX goes to RomFS
ROMGFX		:=	$(filter-out $(MEMGFX) gfx/timelines/%,$(GFXFILES))

TIMELINE_DIRS := $(sort $(dir $(TIMELINE_GFX)))

TIMELINE_FILES := $(foreach dir,$(TIMELINE_DIRS),\
    $(ROMFS)/timelines/$(notdir $(patsubst %/,%,$(dir)))/gfx.t3x \
    $(ROMFS)/timelines/$(notdir $(patsubst %/,%,$(dir)))/gfx.h \
    $(ROMFS)/timelines/$(notdir $(patsubst %/,%,$(dir)))/timeline)

# Directories containing .t3s files, used by VPATH
GFXDIRS		:=	$(sort $(dir $(GFXFILES)))

# Filename of graphics linked into executable
MEM_T3XFILES	:=	$(notdir $(MEMGFX:.t3s=.t3x))

# Resulting RomFS files
ROM_T3XFILES	:=	$(foreach file,$(ROMGFX),\
				$(ROMFS)/gfx/$(notdir $(file:.t3s=.t3x)))

# Headers generated by tex3ds
T3XHFILES := $(foreach file,$(filter-out gfx/timelines/%,$(GFXFILES)),\
				$(BUILD)/$(notdir $(file:.t3s=.h)))

INVENTORY_FILES := \
	$(ROMFS)/inventory/inventory \
	$(ROMFS)/inventory/gfx.t3x \
	$(ROMFS)/inventory/gfx.h

#---------------------------------------------------------------------------------
# Search paths
#---------------------------------------------------------------------------------
export VPATH := $(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
				$(foreach dir,$(GFXDIRS),$(CURDIR)/$(dir)) \
				$(foreach dir,$(DATA),$(CURDIR)/$(dir))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

#---------------------------------------------------------------------------------
# Object files
#---------------------------------------------------------------------------------
export OFILES_SOURCES :=	$(CPPFILES:.cpp=.o) \
				$(CFILES:.c=.o) \
				$(SFILES:.s=.o)

# IMPORTANT:
# Only MEM_T3XFILES is converted with bin2o and linked into the executable.
# RomFS graphics are NOT included here.
export OFILES_BIN	:=	$(addsuffix .o,$(BINFILES)) \
				$(PICAFILES:.v.pica=.shbin.o) \
				$(SHLISTFILES:.shlist=.shbin.o) \
				$(addsuffix .o,$(MEM_T3XFILES))

export OFILES := $(OFILES_BIN) $(OFILES_SOURCES)

#---------------------------------------------------------------------------------
# Generated headers
#---------------------------------------------------------------------------------
export HFILES := $(PICAFILES:.v.pica=_shbin.h) \
			 $(SHLISTFILES:.shlist=_shbin.h) \
			 $(addsuffix .h,$(subst .,_,$(BINFILES))) \
			 $(patsubst %.t3s,%.h,$(notdir $(filter-out gfx/timelines/%,$(GFXFILES))))

#---------------------------------------------------------------------------------
# Include / library paths
#---------------------------------------------------------------------------------
export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
				$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
				-I$(CURDIR)/$(BUILD)

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib)

export _3DSXDEPS	:=	$(if $(NO_SMDH),,$(OUTPUT).smdh)

#---------------------------------------------------------------------------------
# Icon
#---------------------------------------------------------------------------------
ifeq ($(strip $(ICON)),)
	icons := $(wildcard *.png)
	ifneq (,$(findstring $(TARGET).png,$(icons)))
		export APP_ICON := $(TOPDIR)/$(TARGET).png
	else
		ifneq (,$(findstring icon.png,$(icons)))
			export APP_ICON := $(TOPDIR)/icon.png
		endif
	endif
else
	export APP_ICON := $(TOPDIR)/$(ICON)
endif

#---------------------------------------------------------------------------------
# SMDH
#---------------------------------------------------------------------------------
ifeq ($(strip $(NO_SMDH)),)
	export _3DSXFLAGS += --smdh=$(CURDIR)/$(TARGET).smdh
endif

#---------------------------------------------------------------------------------
# RomFS
#---------------------------------------------------------------------------------
ifneq ($(ROMFS),)
	export _3DSXFLAGS += --romfs=$(CURDIR)/$(ROMFS)
endif

.PHONY: all clean

#---------------------------------------------------------------------------------
# Main outer target
#---------------------------------------------------------------------------------
all: $(BUILD) $(ROMFS)/gfx $(MEM_T3XFILES:%=$(BUILD)/%) $(ROM_T3XFILES) $(T3XHFILES) $(TIMELINE_FILES) $(INVENTORY_FILES)
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile

#---------------------------------------------------------------------------------
# Directories
#---------------------------------------------------------------------------------
$(BUILD):
	@mkdir -p $@

$(ROMFS)/gfx:
	@mkdir -p $@

#---------------------------------------------------------------------------------
# Clean
#---------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) $(TARGET).3dsx $(OUTPUT).smdh $(TARGET).elf $(ROMFS)/timelines $(ROMFS)/inventory
	@rm -f $(ROMFS)/gfx/*.t3x

#---------------------------------------------------------------------------------
# Lint
#---------------------------------------------------------------------------------

lint:
	@$(MAKE) CFLAGS="$(CFLAGS) -fanalyzer"

#---------------------------------------------------------------------------------
# gfx_inventory:
# Build into BUILD so it can later be converted by bin2o.
#---------------------------------------------------------------------------------
$(BUILD)/%.t3x $(BUILD)/%.h: %.t3s
	@echo $(notdir $<)
	@tex3ds -i $< \
		-H $(BUILD)/$*.h \
		-d $(DEPSDIR)/$*.d \
		-o $(BUILD)/$*.t3x

$(ROMFS)/timelines/%/gfx.t3x $(ROMFS)/timelines/%/gfx.h &: gfx/timelines/%/gfx.t3s
	@echo $(notdir $<)
	@mkdir -p $(ROMFS)/timelines/$*
	@tex3ds -i $< \
		-H $(ROMFS)/timelines/$*/gfx.h \
		-d $(DEPSDIR)/gfx_$*.d \
		-o $(ROMFS)/timelines/$*/gfx.t3x

$(ROMFS)/timelines/%/timeline: gfx/timelines/%/timeline
	@mkdir -p $(ROMFS)/timelines/$*
	@cp $< $@

$(ROMFS)/inventory/gfx.t3x $(ROMFS)/inventory/gfx.h &: inventory/gfx.t3s
	@echo $(notdir $<)
	@mkdir -p $(ROMFS)/inventory
	@tex3ds -i $< \
		-H $(ROMFS)/inventory/gfx.h \
		-d $(DEPSDIR)/gfx_inventory.d \
		-o $(ROMFS)/inventory/gfx.t3x

$(ROMFS)/inventory/inventory: inventory/inventory
	@mkdir -p $(ROMFS)/inventory
	@cp $< $@

#---------------------------------------------------------------------------------
# All other graphics:
# Build the .t3x into RomFS.
# The generated header remains in BUILD.
#---------------------------------------------------------------------------------
$(ROMFS)/gfx/%.t3x $(BUILD)/%.h: %.t3s
	@echo $(notdir $<)
	@tex3ds -i $< \
		-H $(BUILD)/$*.h \
		-d $(DEPSDIR)/$*.d \
		-o $(ROMFS)/gfx/$*.t3x

#---------------------------------------------------------------------------------
else
#---------------------------------------------------------------------------------
# Inner make
#---------------------------------------------------------------------------------

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
$(OUTPUT).3dsx	:	$(OUTPUT).elf $(_3DSXDEPS)

$(OFILES_SOURCES) : $(HFILES)

$(OUTPUT).elf	:	$(OFILES)

#---------------------------------------------------------------------------------
# Binary data
#---------------------------------------------------------------------------------
%.bin.o %_bin.h : %.bin
	@echo $(notdir $<)
	@$(bin2o)

#---------------------------------------------------------------------------------
# Only .t3x files present in BUILD will arrive here.
# In our case: gfx_inventory.t3x.
#---------------------------------------------------------------------------------
.PRECIOUS	:	%.t3x %.shbin

%.t3x.o %_t3x.h : %.t3x
	$(SILENTMSG) $(notdir $<)
	$(bin2o)

#---------------------------------------------------------------------------------
# Shaders
#---------------------------------------------------------------------------------
%.shbin.o %_shbin.h : %.shbin
	$(SILENTMSG) $(notdir $<)
	$(bin2o)

-include $(DEPSDIR)/*.d

#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------